### ISSUE TITLE
Deleting license does not delete registered domains

### ISSUE THREAD

**Issue by sgehrman** [Arsenal21/software-license-manager#1]
I'm doing some testing.  Deleted all my licenses, but the registration table still has domains in it.  Why don't you delete from that table when deleting a license?

**Comment by Arsenal21** [comment]
I will update the code to also delete the domains for a key.

**Comment by sgehrman** [comment]
cool, thanks!

**Comment by Arsenal21** [comment]
The new version will resolve this.
