### ISSUE TITLE
Is it correct, that a successful License creation returns error_code:10 ('error_code' => SLM_Error_Codes::CREATE_FAILED) ?

### ISSUE THREAD

**Issue by DragonflyNet67** [Arsenal21/software-license-manager#11]
First of all thank you very much for this absolutely great plugin. I love it. 
Whenever I call the API with 'slm_create_new' I get in the JSON Output "result:success", License successfully created as message but also an "error_code":10

I think this comes from the following Line in the API-Listener:
https://github.com/Arsenal21/software-license-manager/blob/a875ded21b8f82da41e80425aee2a70682a26653/software-license-manager/includes/slm-api-listener.php#L69

**Comment by Arsenal21** [comment]
Thank you. I have fixed it.
