### ISSUE TITLE
When to generate a license in woocommerce?

### ISSUE THREAD

**Issue by sgehrman** [Arsenal21/software-license-manager#14]
Hey, I finally launched my app using this package.  Works great for credit card payments, but my code doesn't work well with PayPal.  I'm currently generating the license key on woocommerce_order_status_completed. But with PayPal, it sends an IPN message when complete which sometimes  comes in a second late. Paypal then forwards the user to the Thank you page and there I display the license keys, but if the order is not completed, it's blank.  Know anything about Woocommerce?  I may be willing to pay for support if needed, I'm not much of a WP expert to know the best ways of patching. I've been  debugging this for weeks now.

**Comment by luizbills** [comment]
Try `woocommerce_order_status_processing` hook

**Comment by wpsolutions** [comment]
If you are still having issues you should use PayPal's **Payment Data Transfer (PDT)**.
See this:
https://docs.woocommerce.com/document/paypal-standard/

If you need more assistance developing this get in touch with me - I'm a wordpress developer.
