### ISSUE TITLE
Error codes would be nice

### ISSUE THREAD

**Issue by sgehrman** [Arsenal21/software-license-manager#2]
right now the API returns something like  error, message="Already activated on this domain".  It would be great if it also returned a code or a string like 'error_already_activated' that we can reliably use to form our own error message.  Or return error: -34;  // already activated.  

That is simple to add and would be helpful for my project.

**Comment by Arsenal21** [comment]
Thats a good idea. It will probably be better to add an extra argument like something called "response_code".

Then the response will look something like the following:

result => error
message => License creation failed
response_code => 34

**Comment by Arsenal21** [comment]
This has been implemented

**Comment by sgehrman** [comment]
It would be cool if you could post the latest build to wordpress with error codes.  I don't plan on any more changes and would like to use the 'official' version on my site.  thanks.

**Comment by Arsenal21** [comment]
Done.
