### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by mikeott** [Arsenal21/software-license-manager#27]
On my local development instance of WordPress, I now get this error while running v 4.5.1:

**Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected ')' in E:\www\franken-apps\wp-content\plugins\software-license-manager\menu\slm-add-licenses.php on line 263**

VSCode also complains about the error when I open the file:

**{
	"resource": "/e:/www/franken-apps/wp-content/plugins/software-license-manager/menu/slm-add-licenses.php",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "syntax error, unexpected ')'",
	"startLineNumber": 263,
	"startColumn": 15,
	"endLineNumber": 263,
	"endColumn": 1.7976931348623157e+308
}**

This error doesn't show on production using the same version of the plugin, but perhaps errors are being suppressed in that environment.

If it helps to know, my environments:

**Production:** PHP 7.4.23
**Development:** PHP 7.2.30

**Comment by erommel** [comment]
Hi.

Indeed, PHP 7.2.x does not support this syntax.

Even though PHP 7.2.x has reached EOL some time ago and no longer officially supported (https://www.php.net/supported-versions.php), I will change the syntax in order for the code to be runnable on PHP 7.2.x. This shouldn't be too difficult as we're not using any new features of PHP 7.x branch at the moment.

**Comment by erommel** [comment]
Done. Please test this and let me know if there are any issues.

**Comment by mikeott** [comment]
> Done. Please test this and let me know if there are any issues.

Works like a charm. Props for the speedy fix. Consider the issue closed.
