### ISSUE TITLE
Plugin is not safe

### ISSUE THREAD

**Issue by karchung0930** [Arsenal21/software-license-manager#29]
I think the plugin still cannot protect our plugin/theme. People could have just downloaded them, open them with a code editor, and then delete these lines by the software license manager. This way there is no authentication needed and the plugin act like normal again.

**Comment by Arsenal21** [comment]
This plugin is a basic license server. Not for protecting a plugin. You can look for a different solution. As far as I know, you can't protect a GPL plugin's code.
