### ISSUE TITLE
needs some wp_unslash() to prevent bugs

### ISSUE THREAD

**Issue by sgehrman** [Arsenal21/software-license-manager#3]
I hit a bug in my code where if I passed single quote in the domain (like Steve's domain), SLM gets the $_REQUEST['registered_domain'], that will contain a slash Steve\'s domain.  

I'm somewhat of a WP noob, but it seems it's recommended to always call wp_unslash().  

Your code:
            $fields['registered_domain'] = trim(strip_tags($_REQUEST['registered_domain'])); 

should be:

            $fields['registered_domain'] = trim(strip_tags( wp_unslash( $_REQUEST['registered_domain'] ));

I realize normal domains don't have slashes, but I'm using the domain as a computer name for desktop apps.

Does that make sense?  I can fix it and issue a pull request if you agree.

Thanks.

**Comment by Arsenal21** [comment]
I have merged your changes.
